// File generated by `flutterfire configure` — except the values below are
// intentionally BLANK placeholders. The app detects this and runs fully
// offline (local-first) until real values are pasted in and
// `kCloudBackendEnabled` is flipped to true (see lib/config/cloud_config.dart).
//
// Ask the project owner to create a free Firebase project (Spark plan:
// Authentication + Firestore) and either run `flutterfire configure` to
// regenerate this file, or fill in the blanks:
//
//   1. Firebase console -> Project settings -> "Your apps" -> Web/Android/iOS
//   2. Copy apiKey, appId, messagingSenderId, projectId, etc. below.
//   3. Set kCloudBackendEnabled = true.
//   4. `flutter pub get && flutter run` — sign-in + Firestore sync activate.
//
// Nothing else in the codebase needs to change.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to add support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---- PASTE REAL VALUES HERE (currently blank on purpose) ----
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
  );

  /// True only when real keys have been pasted in.
  static bool get isConfigured =>
      web.apiKey.isNotEmpty && !web.apiKey.startsWith('__');
}
